### ISSUE TITLE
perf: Don't Construct Entire Navmap Tree

### ISSUE THREAD

**Issue by askvortsov1** [ocaml/ocaml.org#1104]
I'm loving the centralized package documentation site! One issue I noticed is very poor performance  on the API reference page for packages with a lot of modules (`core` is a huge offender, but `bonsai`, `eio`, etc all have similar issues).

It looks like `Navmap.nested_render` is recursively constructing HTML for every module/library/etc in the source, which can grow comically large: some `core` pages are a whopping 23.4MB of HTML, a whopping 98% of which is just the navmap.

This feels like a good case for only loading HTML for the elements that should initially be visible, and adding in the rest when needed by the client. Unfortunately, I don't believe HTMX has a clean way to do this, unless toggling the dropdown arrows acted the same way as just clicking the navmap entry. Embedding a small react/mithril/bonsai app would fix this, but would add an unacceptable amount of codebase complexity.

On a side note, it might be nice to add loading indicators somewhere. Even for packages with few modules like cmdliner, there's a 300-500ms response time when clicking into another navmap entry. The page freezes while this transition is happening, which feels slow and uncoordinated.

**Comment by sabine** [comment]
@askvortsov1 Indeed.

I felt tempted before to add a component that renders the Navmap.
From a maintenance perspective, I would prefer Elm as it is a language that is both in the ML-family and designed to be very easy to learn. It's not OCaml, but it feels less dirty than reaching to React et al.

I think that, when we have a working in-package search to jump to identifiers, we could alternatively cut off the collapsed Navmap branches, making the tree structure rendered into the HTML page a less powerful but also much less wasteful navigation. To navigate the full module tree of the package, you would instead type into the search box.

Thank you for pointing at the worst packages in this regard. I only see 4.66MB for the HTML of https://ocaml.org/p/core/latest/doc/index.html (which includes mostly the navmap and little other content), but I agree that this is way too much - in particular since every htmx load has to swap in this huge navmap.

**Comment by askvortsov1** [comment]
Agree that search would be an easier way to navigate around.

I was thinking about this a bit more. If we did want to partially render the navmap, one option could be rendering "current visible items + 1 level", and when an item is expanded, we could load in the updated view. Although even then, I'm not sure how useful that would be. I suspect that most people navigate around the docs by clicking on entries moreso than using the little dropdown arrows, so removing the "clickability" feature on those, and cutting off collapsed branches could solve this issue.

On another unrelated note, is Cloudflare or some other CDN being used to cache responses? The ~400ms load time is higher than I'd expect.

**Comment by sabine** [comment]
> I was thinking about this a bit more. If we did want to partially render the navmap, one option could be rendering "current visible items + 1 level", and when an item is expanded, we could load in the updated view.

Yes indeed, that's entirely reasonable now that we have a minimal in-package search up.

> On another unrelated note, is Cloudflare or some other CDN being used to cache responses? The ~400ms load time is higher than I'd expect.

Not yet. Even caching locally on the ocaml.org server itself would improve the situation with respect to latency. I'm still tempted to implement some caching library that can easily be plugged into Dream. 

We're planning to add some instrumentation to get a proper overview of the worst offenders regarding server response times.

I suspect that the package pages (specifically those with large module trees) will be the worst offenders.

**Comment by sabine** [comment]
Closing in favor of https://github.com/ocaml/ocaml.org/issues/1862.
