### ISSUE TITLE
Playground bottom bar overlaps the editor panel

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#1381]
Feedback from Discord (#ocaml.org channel):

> The bottom bar sits above the editor, so the cursor can actually go under it. I feel they should be in the same parent container, where the code editor flexes in column-direction.

and

> [it is hard to use] the find and replace widget in the playground, since currently it always sticks to the bottom of the page

I agree, this would be a really nice first contribution for someone who is comfortable with CSS.

**Comment by itzAk27** [comment]
Actually i not able to find the issue in the website : https://ocaml.org/ can you help me finding where's the issue

**Comment by sabine** [comment]
@itzAk27 there's an open pull request for this issue already which is likely to resolve the issue. The issue occurs on https://ocaml.org/play. You can help by reviewing the PR.

**Comment by contificate** [comment]
> Actually i not able to find the issue in the website : https://ocaml.org/ can you help me finding where's the issue

@itzAk27 

It's quite hard to run into the issue through casual usage - unless you're looking for it.

In case the [PR](https://github.com/ocaml/ocaml.org/pull/1384) gets merged and someone comes across this related issue in the future, the issue being addressed can be seen in the following image:

![image showing bar overlapping](https://github.com/ocaml/ocaml.org/assets/20199633/d6ab0d53-9ffc-4740-b80a-f1411b25a883)

It's a combination of the following:
- The bar containing the "Run" button is positioned `absolute`ly, this causes the editor to effectively sit underneath it (rather than adjacent to it).
- At certain points of resizing the browser window, it becomes clear that the editor and output pane don't actually flex to the full height of the page.

This is quite minor in the grand scheme of things, but it causes the find-and-replace component (accessible via `Ctrl+f` and visible in the above screenshot) to stick to the very bottom of the editor, underneath the bar (if there is a sufficient number of lines in the editor).

The hope is that the restructured layout will be easier to work with in the case of adding extra UI elements (for example, to facilitate feature requests mentioned elsewhere - such as adding configurable `vim` and `emacs` modes).
