### ISSUE TITLE
Add `;;` to all of the MDX blocks

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ocaml.org#162]
For mdx 3 we will need to add `;;` to all of the toplevel blocks that need them. This is a manual process and won't be that much fun, but might be slightly less boring for any new-to-OCaml folk who would have to *look* at a lot of OCaml code. At the moment we get a lot of warnings from mdx when you run `make test`. 

See the related PR here: https://github.com/realworldocaml/mdx/pull/346

**Comment by Lontchi12** [comment]
Please Sir @patricoferris can you throw more light on this issue so i can work on it? where are the toplevel blocks for mdx 3 so i can add the` ; ; `and also don't know if i can work on this issue while i have an open PR on issue #9

**Comment by patricoferris** [comment]
Hi @Lontchi12, let's wait for all outstanding PRs to be merged before assigning new issues. It gives other folk a good change to have a go too :)) Thank you for the enthusiasm though

**Comment by steph237** [comment]
Please sir @patricoferris I am an outreachy intern applicant and I will like to work on this issue. Can you explain further where I can find the mdx 3 so I add the  ; ;

**Comment by patricoferris** [comment]
Hi @steph237 :)) Do you have the project set up? We've asking for folks to have this done before being assigned/working on an issue?

**Comment by steph237** [comment]
Okay let me set it up right away

**Comment by Lontchi12** [comment]
Hello @patricoferris can i work on this project?? Don't know if @steph237 is still interested my PR has been merged already

**Comment by Lontchi12** [comment]
Hello I'm still waiting a response on this issue. Can i work on this issue??? @tmattio

**Comment by tmattio** [comment]
Hi @Lontchi12 🙂 Apologize for the late answer, the GitHub notification somehow slipped through the cracks. Sure, feel free to work on this.

**Comment by Lontchi12** [comment]
Thank you @tmattio Please can you throw more light on this so i can start right away?

**Comment by tmattio** [comment]
When you run `make test` in the project, you'll see a lot of warnings like:

```
Warning: OCaml toplevel block without trailing ;; detected in file '033_is_coprime.md'.
Non-semicolon terminated phrases are deprecated.
MDX 2.0 will accept them as input but will output them with ;; appended.
In MDX 3.0 support for toplevel blocks without ;; will be removed completely.
```

This is because with the latest mdx (the program that executes the code block in markdown files) the toplevel sentences (OCaml sentences that start with `#`), need to end with `;;`.

For instance, here's a patch that fix the warning for `033_is_coprime.md`:

```diff
diff --git a/data/problems/en/033_is_coprime.md b/data/problems/en/033_is_coprime.md
index 66c7f0a..d1cd3c7 100644
--- a/data/problems/en/033_is_coprime.md
+++ b/data/problems/en/033_is_coprime.md
@@ -14,7 +14,7 @@ let rec gcd a b =
 
 ```ocaml
 # (* [gcd] is defined in the previous question *)
-  let coprime a b = gcd a b = 1
+  let coprime a b = gcd a b = 1;;
 val coprime : int -> int -> bool = <fun>
 ```

The goal of this issue is to find all the instances of toplevel sentences that don't end with `;;` and correct them. If that helps, the warnings I see are coming from these files:

```
001_a_first_hour_with_ocaml.md
004_data_types_and_matching.md
005_lists.md
006_functional_programming.md
007_flatten_list.md
007_if_statements_loops_and_recursion.md
008_modules.md
009_labels.md
010_pointers.md
010_run_length_encoding.md
011_modified_run_length.md
011_null_pointers_and_warnings.md
012_functors.md
013_objects.md
014_error_handling.md
015_common_error_messages.md
016_debug.md
017_map.md
017_split_list.md
018_extract_slice.md
018_set.md
019_hashtbl.md
020_streams.md
021_format.md
022_create_list.md
026_generate_combinations.md
027_group_elements.md
027_performance_and_profiling.md
031_is_prime.md
032_gcd.md
033_is_coprime.md
034_euler_totient.md
035_prime_factor.md
036_prime_factor_2.md
038_compare_totient.md
039_list_prime.md
040_goldbach_conjecture.md
041_goldbach_composition.md
046_truth_table.md
048_truth_table_2.md
050_huffman_code.md
055_balanced_btree.md
056_symmetric_btree.md
057_bst.md
058_generate_and_test.md
059_height_balanced_btree.md
060_height_balanced_btree_2.md
061_count_leaves.md
063_create_btree.md
064_btree_layout_1.md
065_btree_layout_2.md
066_btree_layout_3.md
067_string_of_btree.md
068_sort_btree.md
070C_count_mtree_nodes.md
070_create_mtree.md
071_internal_path.md
072_bottom_up_seq.md
073_lisp_of_mtree.md
080_conversions.md
081_node_path.md
082_node_cycle.md
083_spanning_trees.md
084_minimal_splanning_tree.md
087_depth_first_traversal.md
091_eight_queens.md
095_english_number_words.md
096_syntax_checker.md
097_sudoku.md
098_nonograms.md
```

**Comment by Lontchi12** [comment]
Wooohhh that's a whole lots of files, Okay no problem let me get to it right away. Thanks for the explicit explanation @tmattio

**Comment by Lontchi12** [comment]
Hello @tmattio i have an issue with this file 007_if_statements_loops_and_recursion.md, i have an error when i try to put the `;;` at the end of the block in line 1138

`The basics of arrays are simple:

```ocaml
# let a = Array.create 10 0;;
Line 1, characters 9-21:
Alert deprecated: Stdlib.Array.create
Use Array.make/ArrayLabels.make instead.
val a : int array = [|0; 0; 0; 0; 0; 0; 0; 0; 0; 0|]
# for i = 0 to Array.length a - 1 do
  a.(i) <- i
Line 3, characters 1-3:
Error: Syntax error
# a;;
- : int array = [|0; 0; 0; 0; 0; 0; 0; 0; 0; 0|]`

i.e where there is a for loop

**Comment by patricoferris** [comment]
Thanks for finding this @Lontchi12, this is actually an error from when the examples where converted, the problematic expression is missing a `done`. See the original here: https://ocaml.org/learn/tutorials/if_statements_loops_and_recursion.html

**Comment by Lontchi12** [comment]
Thank you @patricoferris I noticed that too so i also checked the original and added the `done` and the `;;` afterwards but i still got the error that's why i came here for help

**Comment by Lontchi12** [comment]
Here is what i did
`The basics of arrays are simple:

```ocaml
# let a = Array.create 10 0;;
Line 1, characters 9-21:
Alert deprecated: Stdlib.Array.create
Use Array.make/ArrayLabels.make instead.
val a : int array = [|0; 0; 0; 0; 0; 0; 0; 0; 0; 0|]
# for i = 0 to Array.length a - 1 do
  a.(i) <- i
  done;;
Line 3, characters 1-3:
Error: Syntax error`

And still got this
`diff --git a/data/tutorials/en/007_if_statements_loops_and_recursion.md b/data/tutorials/en/.mdx/007_if_statements_loops_and_recursion.md.corrected
index b140d7b..316be5c 100644
--- a/data/tutorials/en/007_if_statements_loops_and_recursion.md
+++ b/data/tutorials/en/.mdx/007_if_statements_loops_and_recursion.md.corrected
@@ -1137,10 +1137,9 @@ val a : int array = [|0; 0; 0; 0; 0; 0; 0; 0; 0; 0|]
 # for i = 0 to Array.length a - 1 do
     a.(i) <- i
   done;;
-Line 3, characters 1-3:
-Error: Syntax error
+- : unit = ()
 # a;;
-- : int array = [|0; 0; 0; 0; 0; 0; 0; 0; 0; 0|]
+- : int array = [|0; 1; 2; 3; 4; 5; 6; 7; 8; 9|]
 ```
 Notice the syntax for writing arrays: `[| element; element; ... |]`
 
        lint alias tool/ood-gen/bin/runtest
Testing `Linting'.
This run has ID `73A01B4F-3B39-4A46-882E-32D7B16BAB56'.`

**Comment by patricoferris** [comment]
Yes that is correct, the part where you said 

> And still got this

is a [diff](https://en.wikipedia.org/wiki/Diff) which shows you deleted and added lines, this is how [mdx](https://github.com/realworldocaml/mdx) and dune interact showing you the new result as a `diff` with the old result so you can choose whether or not it is what you intended. This shows that the error is being remove replaced with a successful iteration through the loop (the `+- : unit = ()` line) and the new array has been successfully updated using the code from that loop (the `+- : int array = [|0; 1; 2; 3; 4; 5; 6; 7; 8; 9|]` line). To incorporate the changes you can run `dune promote`

**Comment by Lontchi12** [comment]
Thanks so much @patricoferris problem solved, i want to push now and submit a PR now but i'm realising two files which i haven't touched have changes the file `problem.ml` and the file` tutorial.ml`, will it pose a problem if i push them the way they are too?

**Comment by patricoferris** [comment]
They should have changed :)) We take all the markdown that you've updated and convert it to OCaml code which hopefully are the changes in the `problem.ml` and `tutorial.ml` files. You should be able to inspect the diff of those files to make sure it is those changes.

**Comment by Lontchi12** [comment]
Yes they are, Thanks alot

**Comment by tmattio** [comment]
Done in #176
