### ISSUE TITLE
Create a Dedicated Page for Individual Books, so the Books on the Learn Overview Page Link Somewhere

### ISSUE THREAD

**Issue by AndroGenius-codes** [ocaml/ocaml.org#1640]
Hello @sabine @SaySayo  I was trying to get help from ocaml- documentation and I saw a page for recommended books. Unfortunately there's no way to navigate to the books unless you click on "see more" and a new page opens. 
I don't know if it's by design. 
Here's how to reproduce the error
1. Go to ocaml.org
2. Navigate to "learn"
3. Scroll down to books and try to click on any book.

I was using my  mobile phone so I don't know if it's reproducible with desktop

**Comment by SaySayo** [comment]
This is actually a very valid point. The books on the learn area doesn't lead to a link where it can be read, it only redirects to the books page when you click on see more books. cc @sabine

**Comment by sabine** [comment]
Yes, it seems valid to make free books on the Learn overview page link directly to their websites.

**Comment by sabine** [comment]
# Task

Create a dedicated page for every book, so that the books blocks from the Learn Overview page can link to it.

1. Create a new template `book.eml` that renders a single book, similar to `books.eml`. Be careful about indentation, the templating engine used in this project is sensitive to it.
2. Add a rule to the dune file at `src/ocamlorg_frontend/dune` to process the `book.eml` template into an OCaml module `book.ml`.
3. Add a function for the new template to `ocamlorg_frontend.ml`.
4. Add a handler `book` to `handler.ml` that looks up the book by its slug and renders the new template.
5. Add a route for the new page to `src/global/url.ml` and register the handler from the previous step it in the router at `router.ml`.

**Comment by sabine** [comment]
@godplayer56 when I wrote this down, I realized this is more like a medium issue already, but do give it a try. :slightly_smiling_face:

**Comment by sabine** [comment]
@godplayer56 you are now assigned to this issue. Have fun!

**Comment by Raven49** [comment]
Hi @sabine @SaySayo  , I have made my first contribution as #1658  Kindly assign me any new task so that i can contribute for Outreachy.

**Comment by sabine** [comment]
@Raven49 you have commented this same request on 5 different issues, which is quite disruptive in how it makes GitHub link up the issues and PRs.

Regardless, I'll try and see if I can make another medium issue for dark mode.

**Comment by Raven49** [comment]
Sorry @sabine it's just because I was unable to get myself a task .

**Comment by SaySayo** [comment]
Hi @godplayer56, Are you still working on this? If yes, you can open a draft pull request to get some review on your work.

**Comment by AndroGenius-codes** [comment]
@godplayer56 hello how is this going? Do you need any help

**Comment by godplayer56** [comment]
Hey @AndroGenius-codes , I was busy learning Ocaml and studying the project so I haven't made much progress over this issue😅, you can assign this issue to someone else meanwhile if I make significant progress in this I'll open a draft PR and inform you🤗. Really sorry for not updating you with what I was working on😅

**Comment by AndroGenius-codes** [comment]
Oh I am not a mentor, Sabine is.

**Comment by sophiatunji** [comment]
Can I be assigned this issue. I'll love to work on it. @SaySayo

**Comment by SaySayo** [comment]
@sophiatunji, You will be assigned this issue. cc @sabine

**Comment by sabine** [comment]
Unfortunately, this issue became obsolete with the new Learn Area UI.
