### ISSUE TITLE
Add a Jump To Top Button

### ISSUE THREAD

**Issue by oyenuga17** [ocaml/ocaml.org#1687]
While browsing through the site, I noticed it wasn't very convenient to navigate to a new page when I'm at the bottom of the page. I always have to scroll back to the top to see the header before I can navigate

Did a little experiment with this on the browser and I think having a sticky header might be a good enhancement to the user experience.

https://github.com/ocaml/ocaml.org/assets/64274826/0d6342f0-8f31-4a49-9b56-f93f74018b12

@sabine was this left out on purpose or it's a valid enhancement? 🤔 ...

**Comment by sabine** [comment]
It reduces the amount of space there is for reading the actual pages. (Tall sticky headers are an anti-pattern because of the space they take up.)

The designs however include a button to jump back to the top of the page which would be a great addition to implement!

https://www.figma.com/file/bL31M0WWTTdu2z9jAOX77J/UX%2FUI-OCaml-Learn-Area?type=design&node-id=624%3A2385&mode=dev&t=XIGqREQZJEsqCAJ0-1

![Screenshot from 2023-10-19 17-45-18](https://github.com/ocaml/ocaml.org/assets/6594573/bb182bd9-481b-4bd2-be77-18790335d0e2)

**Comment by oyenuga17** [comment]
hmm, that's true this is much better. 
@sabine can I work on this while I wait for your response on #1642?

**Comment by sabine** [comment]
@oyenuga17 sounds fine to me, thanks for bringing this up! I assigned you.
