### ISSUE TITLE
very bad documentation

### ISSUE THREAD

**Issue by dmuiX** [ocaml/ocaml.org#1845]
i tried to write this
# let square x = x * x
val square : int -> int = < fun >
# square 3

in the playground

does not work

and its not written in get started how to build a function and run it
do i need to setup a main function to run anything?

**Comment by sabine** [comment]
https://ocaml.org/play#code=bGV0IHNxdWFyZSB4ID0geCAqIHg7OwoKc3F1YXJlIDM%3D

The only thing that you needed here was the `;;` delimiter.

The playground is a bit quirky in the sense that it behaves more like writing an OCaml file, instead of as a REPL. My impression is we need to provide an online REPL to run the examples from the tutorials.

I think we probably should add a small tutorial on using the playground.

**Comment by dmuiX** [comment]
Thanks. Yeah It’s actually not a very motivating start when you type that example in the playground and it does not work. Especially as a beginner in ocaml.
Would definitely be a good idea to have a tutorial for the playground!
So where is that documented? I did not see that in the get started docs. is that somewhere deeper?

**Comment by sabine** [comment]
That's the thing: I don't think this is documented anymore after we rewrote the tutorials in the Getting Started section. I opened an issue to add this at https://github.com/ocaml/ocaml.org/issues/1853. :+1:
