### ISSUE TITLE
Creating a fork for a sibling site for Coq/Rocq

### ISSUE THREAD

**Issue by tabareau** [ocaml/ocaml.org#1917]
Dear OCaml.org maintainers team,

The Coq development team appreciates the work you have done on the new OCaml website 
and we will be interesting in reusing part of it for the new website that we want to launch together
with the change of name to `the Rocq prover`.

Therefore, we have several questions: 

- is it possible from a license point of view ?
- is there any part of the website that we should/can not reuse ?
- do you think it is envisageable technically to simply do a fork on which we can rebase any modification you made ?

Best,

**Comment by sabine** [comment]
> is it possible from a license point of view ?

Looking at

https://github.com/ocaml/ocaml.org/blob/main/LICENSE

I can see that the code of ocaml.org is licensed under ISC, which means making a fork and changing that as you need would be no problem. The only relevant condition here would be that the ISC copyright notice is kept around to mention that part of the code came from here.

> is there any part of the website that we should/can not reuse ?

According to the license, the visual design should not be reused, so I think that this is something that would need to be treated carefully and/or discussed in detail. For example, if you did a reskin of the pages that you want to keep with different TailwindCSS styles, that would most likely be sufficient, since you will also be changing the content of the pages, probably removing some pages and adding others.

> a fork on which we can rebase any modification you made

My assumption is that you'd probably have to strip down the code significantly, and remove some parts of the site, to bring it into a state where you have a maintainable and clean codebase. At this point it is probably going to be difficult to keep rebasing on ocaml/ocaml.org, considering the pace at which ocaml.org is changing.

However, taking OCaml.org as a starting point of a new codebase, or as inspiration seems valid to me. Would recommend to wait on a response from @tmattio, though. :slightly_smiling_face:

**Comment by sabine** [comment]
I think the main points have been addressed. Closing this.
