### ISSUE TITLE
Learn Guidelines: recommend ocamlformat, remove formatting text

### ISSUE THREAD

**Issue by mndrix** [ocaml/ocaml.org#240]
The [Best Practices](https://v3.ocaml.org/learn/best-practices) document recommends `opam install ocamlformat`. Much of what's recommended in the [Programming Guidelines](https://v3.ocaml.org/learn/ocaml-programming-guidelines) document is what ocamlformat already does automatically.  Would it be better to remove formatting guidelines and focus on guidelines that aren't automated (sections like Opening Modules, Pattern Matching, Loops, etc)?

If so, I'm glad to submit a pull request.

**Comment by avsm** [comment]
I'm in favour of that in principle, but a high-level question I have is how well the ocamlformat defaults implement the suggestions in the Programming Guidelines. It's worth checking that they're consistent, and then recommending ocamlformat.

cc @gpetiot

**Comment by gpetiot** [comment]
We used to have an issue about that: https://github.com/ocaml-ppx/ocamlformat/issues/501
Some points are handled by the default behavior, some require to use a specific option.

However we are moving away from this option-centric usecase of ocamlformat, to try to use push a smaller set of behaviors (profiles) that have their own consistency, e.g.:
- print symbols/keywords on the left to avoid having to look horizontally to have an insight of the structure of the code (the `ocamlformat` profile)
- playing well with ocp-indent (the `janestreet` profile)
- reduce the vertical diff when lines are added/removed (a possible future for the default profile)
- style most commonly used by the community (the `default` profile)

These profiles are not driven by the guidelines since they have their own consistency. Of course it's possible to open issues on ocamlformat if you think some of the guidelines may make sense for some profiles, but I don't think it should become a specification for ocamlformat (we already have a lot of technical challenges and constrants and some behaviors are really hard to achieve).

**Comment by mndrix** [comment]
> we are moving away from this option-centric usecase of ocamlformat, to try to use push a smaller set of behaviors (profiles) that have their own consistency

I think that's an excellent direction. I use ocamlformat in its default configuration, even when it disagrees with the Guidelines or my personal preferences. I think that a consistent format is more important than which format is chosen; and ocamlformat's defaults are quite good.  I see the OCaml Programming Guidelines on the new website as an opportunity to encourage new users towards modern tools and ocamlformat's default style.

As a newcomer to OCaml myself, I'd rather see "Don't worry about formatting your code by hand; let ocalmformat do that.  Now let's talk about some guidelines for OCaml code that aren't automated: …".

So, my concrete proposal is that I remove all formatting discussion from Guidelines, even when it deviates from ocamlformat defaults, and focus the Guidelines on everything else. The pull request would essentially be deletions.
