### ISSUE TITLE
Link to specific platform installation instructions

### ISSUE THREAD

**Issue by dra27** [ocaml/ocaml.org#2583]
https://ocaml.org/install automatically displays the Windows page when viewed from a Windows machine, but it would be nice if it updated the URL with an anchor (i.e. such that https://ocaml.org/install#windows activates the Windows instructions anywhere and https://ocaml.org/install#{unix,linux,macos,bsd,etc.} activates the Linux instructions) so that it can be referenced directly.

**Comment by sabine** [comment]
Yes, this would be nice, and also it's a small task that could be contributed by a newcomer.

**Comment by Gbury** [comment]
I tried using the new anchors, but on my machine (a linux one), if I try to go explicitly to the windows instructions from a link (i.e. https://ocaml.org/install#windows or even by refreshing the webpage after clicking on the windows instructions), the page automatically redirects to the linux installation instructions, which is really counter-intuitive and annoying, since the link was explicitly to the windows instructions.

I guess that's why this issue is not closed yet ?

**Comment by piotr-m-jurek** [comment]
What would be the ideal scenario to resolve this issue?
1. when someone sends me the link `https://ocaml.org/install` I am presented with the `install` page and none of the options are chosen
2. when someone sends me the link `https://ocaml.org/install#windows` and it matches my system I'm presented with the `install#windows` page (same for the other option).
3. when someone sends me the link `https://ocaml.org/install#windows` and it doesn't match my system, I'm being redirected to `install#linux_mac_bsd` page.

**Comment by Gbury** [comment]
I'd say the ideal scenario would be to have all the following points be true:
- when someone follows a link to `https://ocaml.org/install`, redirect to the page that matches the user's system
- when someone follows a link to `https://ocaml.org/install#foo`, present the page for `foo` (i.e. either `windows` or `linux_mac_bsd`) regardless of the system. If the anchor is part of the url being clicked on/followed, then it means that there was some intent to link to these specific instructions, and overriding it seems not great.
