### ISSUE TITLE
Support documentation dark mode

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#31]
See https://github.com/tailwindlabs/tailwindcss-typography/issues/69 for the content

**Comment by MuluhGodson** [comment]
@tmattio Greetings. Can I handle this issue?

**Comment by tmattio** [comment]
@MuluhGodson We're working heavily on the frontend, and I'm not sure how this issue fits with the work we're doing, may I suggest choosing a different issue?

**Comment by MuluhGodson** [comment]
Okay great.

**Comment by danawoodman** [comment]
Would be great if the site supported dark mode so that my retinas aren't permanently seared from reading the docs 😅 

From a quick look at the code seems a lot of the basics are there: Tailwind with some semantic class names. Assuming its just missing the dark version's overrides of Tailwind's styles and a few other related tweaks.

**Comment by sabine** [comment]
Closing in favor of https://github.com/ocaml/ocaml.org/issues/1559
