### ISSUE TITLE
`opam install graphics` in the "A First Hour with OCaml" tutorial requires logout+login on MacOS

### ISSUE THREAD

**Issue by DrTobe** [ocaml/ocaml.org#629]
I have been following the "A First Hour with OCaml" tutorial on MacOS. In the "A Module From Opam" section, I installed the `graphics` module which automatically checks that XQuartz is installed and offers to install it if not found. Unfortunately, this was not enough to run the examples below because XQuartz apparently needs logout+login to be usable. There is no helpful error message so this feels a little bit disappointing in a section about "a very simple cross-platform" module.

So I want to suggest adding a small note there to save others from potential frustration. But I could also understand if you do not think that this belongs in the OCaml tutorial. Then, just feel free to close/ignore this.

**Comment by DrTobe** [comment]
Please ignore this. I checked again and there _is_ a "installer: The install requires logging out now." line.

**Comment by shindere** [comment]
Many thanks, @sabine, for your interest in improving this asppect of the
website. I am fully convinced that this is a fundamental issue and
that many improvements do have this prerequisite that the generated
HTML code is valid.

May I suggest to slightly modify the terminology in this issue to mmake it
more pprecise? To be more precise myself, I think `invalid HTMML` would be
clearer and more well-defined than `broken` HTML.

The HTML not being valid does indeed mmake it possible that the rendering
varies between browsers, because the way a browser renders HTML is well
defined only if the HTML is valid. If it is not, then the browser will
render it as best as it can but the way to recover from invalid HTML is
browser-specific and has thus no reason to be consistent from one browser to
the other. this of course imppacts accessibility but the impact is much
broader.

Thanks again! Very well done!

**Comment by cuihtlauac** [comment]
@shindere: I'm under the impression you may have posted this comment to the wrong issue. It seems to make sense with respect to https://github.com/ocaml/ocaml.org/issues/829
