### ISSUE TITLE
Package documentation headings formating including <code>

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#673]
PR https://github.com/ocaml/ocaml.org/pull/639 has a small bug on section titles when then include &lt;code&gt; see, for instance:

https://ocaml.org/p/opam-monorepo/0.3.2/doc/index.html#opam-monorepo-docs

![Screenshot_2022-12-05_11-48-08](https://user-images.githubusercontent.com/1917592/205619138-1a83046c-53d7-4549-ba85-96cd46175be0.png)

**Comment by sabine** [comment]
What exactly is the bug in relation to #639? It looks normal to me:

![Screenshot 2022-12-05 at 12-19-59 Documentation · opam-monorepo 0 3 2 · OCaml Packages](https://user-images.githubusercontent.com/6594573/205625012-83ed5f99-34c3-4f6c-a2ca-0a35c708d6e0.png)

Can you try to reload the page (disable cache via the network tab of your browser)?

**Comment by cuihtlauac** [comment]
I find the difference of font bitween “opam monorepo” and “Docs” a bit weird, don't you?

**Comment by sabine** [comment]
Oh, that. Apparently, that's how the package author wrote the heading. There's no connection to #639 as the patch did nothing with respect to fonts. 

I agree, this looks jarring.

Two options: 
1. set the font family for `h1 code, h2 code`, etc. to the heading font family
2. Play with styles to make it look at least a bit more intentional/similar (but I think we would need another, stronger, font weight on the monospace font for that) to honor the markup the package authors chose.

**Comment by sabine** [comment]
Ok, so after looking at this a bit more... My impression is that the main dissonance here is that the monospace font has a different font size. And this actually applies to all `code` tags on the site.

The culprit is https://github.com/tailwindlabs/tailwindcss-typography/blob/4c3b76ccc8120f307514d5721598763fd09761c0/src/styles.js#L76-L84.

I can see that GitHub in their own styles also makes the `code` elements smaller, but it tries to offset this by giving them a background color. (I think it looks bad on GitHub too, but it could easily be remedied by increasing the top padding so that the background aligns with the line-height of the surrounding text.)

However, on ocaml.org where we have no background color for the `code` elements, the misalignment just looks way off. Either the `code` elements need to be the same font-size as the surrounding text, or we need to add a background as a visual element to restore the perception of correct alignment.

I believe that it makes sense to sit down and distill the typography used in ocaml.org in such a way that we do not need to use an external dependency (tailwindcss-typography) anymore. That would make it easier to see where the CSS came from and also easier to modify it.

Also, since we want to share styles between ocaml.org, odoc, the OCaml language manaual, omd(?), I believe we need a dependency-free CSS artifact that can be shared between the projects. :thinking:
