### ISSUE TITLE
Sidebar and mld pages

### ISSUE THREAD

**Issue by panglesd** [ocaml/ocaml.org#680]
First, thanks a lot for the new package sidebar: It is really awesome, and so much better than what was before!

I think the sidebar where there are mld pages has some quirks: 
- In https://ocaml.org/p/ppxlib/0.28.0/doc/index.html the pages are not displayed in the list of pages (and thus accessible only from the index page)
- In https://ocaml.org/p/ppxlib/0.28.0/doc/manual.html (an mld page), the sidebar is not populated.

I think it would be nice to always have the full sidebar, with pages first and then the API part (modules etc).
(Also, it would be great to be able to sort the pages, for instance using alphabetical order, until odoc has a proper support for sidebar toc and linear documentation.)
Also, this might be odoc's fault, but I'm opening the issue just in case!

**Comment by sabine** [comment]
@panglesd Agreed.

We do need mld pages to show up in the sidebar. You're correct that, currently, upstream doesn't produce a list of standalone docs pages that we can display, and this is a high-priority issue to solve.

Good point about the sidebar being empty when viewing mld pages. That's an oversight on my part: In order to make the module tree easier to browse on packages with a lot of tree items, I hid all libraries except for the current path. However, since we have a bug where ocaml.org cannot distinguish a module page from a mld page (that's why you see "Module" on the mld page), this hiding is a problem. I'll put in a fix to show the full tree when you're on an unrecognized module page, for now.

The good thing: there's already a patch applied to odoc that will let us distinguish mld pages and module pages  in the near future.


Thanks for the feedback, it is very helpful!
