### ISSUE TITLE
Misc. bugs in documentation

### ISSUE THREAD

**Issue by kumar-ish** [ocaml/ocaml.org#720]
Hi, I've just been reading through the OCaml docs.

### Markdown rendering issue on _If Statements and Loops_ page
There's an issue on [this](https://ocaml.org/docs/if-statements-and-loops) page in which there's an issue with rendering the code block because of incorrect indentation. I've fixed it and pushed changes to [this](https://github.com/kumar-ish/ocaml.org/tree/madhav/fix-if-statements-and-loops-md-indent) branch. I'm happy to open the pull request myself or anyone else to do so.

Before:
![image](https://user-images.githubusercontent.com/47245900/208332172-b41bf7fa-043c-4750-ad21-fd97aab2e051.png)

After:
![image](https://user-images.githubusercontent.com/47245900/208336622-69eab528-ab39-4ff0-98ff-82994503860f.png)

### Minor inaccuracy in documentation
Also just a minor issue: in the same page it says "One feature which I didn't cover: OCaml records can have mutable fields" -- but in the [previous](https://ocaml.org/docs/data-types) section that covered records, it did mention records having mutable fields: "Records may be mutable: ..."

**Comment by cuihtlauac** [comment]
Thanks, @kumar-ish the markdown code is indeed bugged, and yours look way better. Can you create a PR with your branch? We'd love to merge it, and you'll get full credits for it :-)

I'll see what I can do to improve the inaccuracy you pointed out, thanks for that too.

**Comment by kumar-ish** [comment]
Done :)

**Comment by kumar-ish** [comment]
I might just put any other things I notice in this issue since it fits under the Misc. bugs description.

In the [Pointers in OCaml](https://ocaml.org/docs/pointers) page, what is the reason for there to be a `/2` after the list type? (CTRL + F "What about a list of optional ints?") It doesn't seem to show anything like that in the REPL and I can't seem to find anything else that would indicate why that would be there.

**Comment by cuihtlauac** [comment]
This one is not a bug :-) Although the document https://ocaml.org/docs/pointers needs to be updated in order to either:
* explain that `/2`
* remove it

In the standard library, there is a type definition called `list`. You can check it by typing the following in `utop`:
```ocaml
#show list;;
```

It will reply:
```
type 'a list = [] | (::) of 'a * 'a list
```

In the document, there is an additional definition of a type called `list`:
```ocaml
type list = Nil | Cons of cell
 and cell = { mutable hd : int; mutable tl : list };;
```

In OCaml, there are no name clashes. The latter definition is “shadowing” the former. However, as of closures, it does not mean the first definition is gone.

If you type `Nil` the REPL replies:
```ocaml
- : list = Nil
```

meaning: “`Nil` is a `list`, as of the latter definition.”

Then if you type `[]` (also pronounced “nil”) the REPL replies
```ocaml
- : 'a list/2 = []
```

meaning: “`[]` is a `list`, as of the former definition.”

Both `list` types are still there, hence the `\2`.

**Comment by cuihtlauac** [comment]
It's better to have one topic per issue. That's easier to track. This one is now closed, let's move discussions on other topics to other places :-) I've created two additional issues on the other topics you brought, which aren't closed yet.

**Comment by kumar-ish** [comment]
Ahh, okay that makes a lot of sense (I imagine you figured this but I hadn't defined list and was looking at the `list/2` showing up in the REPL in isolation) -- thank you for the clear and thorough explanation! That's a really interesting language feature, I like it 👀 

And yep, I'll be sure to open new issues if I see anything else.
