### ISSUE TITLE
Use Ocsigen repl-in-browser for playground?

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#737]
There is a joint OCaml 5 plus Js_of_ocaml 5 top-level in a browser running here:

http://ocsigen.org/js_of_ocaml/latest/manual/files/toplevel/index.html

It seems to have been set up for the release of Js_of_ocaml 5. Should ocaml.org adopt this set up for the playground?

* UI
* Version & build

**Comment by tmattio** [comment]
The initial playground implementation was actually based on Ocsigen's browser example IIRC, but it's been improved quite a lot since then:
- Syntax highlighting
- Support for code mirror
- RPC protocol for the runtime which gets faster page load time
- Merlin in JS which gets us the syntax error, type on hover, etc.

The Playground now arguably has a much more complete editor experience than Ocsigen's REPL, so let's keep it, but:
- We should definitely upgrade the codebase to OCaml 5 to get support for effects. After trying quickly it seems that the immediate blocker is merlin-js, which is not compatible with OCaml 5 (cc @voodoos)
- Are there specific parts of the UI that you'd like to see in the Playground?

**Comment by tmattio** [comment]
The playground is now compatible with OCaml 5, I think we can close this
