### ISSUE TITLE
Mobile/Tablet Layout is Rendered on Monitors With a High Pixel Density

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#822]
![bdf70f84eeb24fc84cffd77cfa9f9f871d1bd974_2_524x500](https://user-images.githubusercontent.com/6594573/212839416-054832ca-d6b5-45de-90a2-1ab8f8dd6d9f.png)

For some reason, on Mozilla Firefox 91.13.0esr on Debian 11, the Learn page (and possibly other parts of the site) displays the mobile view. It shouldn't do that.

**Comment by cuihtlauac** [comment]
I've tested on Firefox 108.0.2 on Ubuntu 22.10 and could not reproduce it. Could it be a Firefox bug?

**Comment by sabine** [comment]
It's likely that it has something to do with the browser version, or custom settings.

**Comment by talex5** [comment]
(from discuss)
> Thank you for including the browser version - this is quite different from what I see on all the browsers I have installed and clearly not what was intended here. Are there any nonstandard settings (e.g. font size) used?

I normally zoom it to 130%, but it still goes to mobile mode much too soon even at 100% zoom. I can get the regular view if I make the browser window really wide (I have a fairly wide screen and usually have the browser window about 50% of the screen width).

But also, I don't understand why a mobile user would want their entire screen filled with a single link either.

**Comment by sabine** [comment]
@talex5 Indeed, the problem with the height is valid and a separate issue here: https://github.com/ocaml/ocaml.org/issues/823

The open question here is whether ocaml.org is violating any CSS best practices that makes your browser version (and potentially other browsers/versions) display the mobile version at 100% zoom. I remember something about mixing rem and px units potentially causing problems on some browsers.

**Comment by sabine** [comment]
So far unable to reproduce on Firefox 91.0 on BrowserStack Windows/MacOS (BrowserStack unfortunately offers neither the exact Firefox version nor Debian 11). :thinking:

OCaml.org's use of media queries looks unconspicious to me as well, it's using `px`-units throughout (which AFAIK is still the most browser-compatible way to do it).

**Comment by cuihtlauac** [comment]
It looks like it is related to pixel density. I can reproduce the issue on two Chromebooks with high dpi screens. The layout switches to “mobile” when the window size falls under 1024px, however:

* 1200×800@117dpi: 1024px is 22cm (screen width is 26cm)
* 1600×900@140dpi: 1024px is 19cm (screen width is 29cm)

This means in both cases, the mobile layout is used, although the window still occupies more than half of the width and is perfectly legible because of the high pixel density.

@talex5, what kind of screen are you using?
@sabine, are the measurements in px or screen pixels?

P.S.
I suspect the resolutions given above are false, in reality, they're probably even higher. I've used Chrome Dev Tools and the Cog Extension to get them (https://chrome.google.com/webstore/detail/cog-system-info-viewer/). However; device manufacturer specifications say the screens are:
* 12.3 in, 2400×1600 resolution
* 13.3 in, 3200×1800 resolution

Seems a ×2 scaling is taking place to avoid windows being tiny.

**Comment by sabine** [comment]
CSS px measurements generally do not correspond directly to screen pixels, in particular when custom font sizes are used, or the browser window is scaled (e.g. alt-+/-).

**Comment by talex5** [comment]
> @talex5, what kind of screen are you using?

It's fairly high-DPI indeed:
```
$ swaymsg -t get_outputs
Output DP-1 'Samsung Electric Company U32R59x H4ZM801677' (focused)
  Current mode: 3840x2160 @ 59.997 Hz
  Position: 0,0
  Scale factor: 2.000000
```

**Comment by cuihtlauac** [comment]
I believe we're not handling properly that `Scale factor: 2.000000`. I wonder what's the behaviour on a retina display Mac.

**Comment by sabine** [comment]
I think we might have fixed this by making the responsive collapsing of pages depend on `em` units instead of pixels. Closing.

If you're still experiencing this problem, reply so we can reopen and find a setup to debug this on.
