### ISSUE TITLE
Some package overview pages appear quite empty

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#825]
https://ocaml.org/p/ocamlformat/0.24.1# looks like this 

![Screenshot 2023-01-17 at 09-18-36 ocamlformat 0 24 1 · OCaml Package](https://user-images.githubusercontent.com/6594573/212844976-67d98ea0-984a-42f9-952c-d78b6a229e42.png)

while `ocamlformat` has a fine README on their GitHub repository https://github.com/ocaml-ppx/ocamlformat:
![Screenshot 2023-01-17 at 09-19-24 ocaml-ppx_ocamlformat Auto-formatter for OCaml code](https://user-images.githubusercontent.com/6594573/212845117-01d70edd-8f71-4f97-8401-e3043264cae2.png)

In cases like this, I feel that what we actually wanted to show here is the README of the repository instead of the "Description".

Need to look into where this "Description" is set and decide how to deal with cases like this (e.g. tell the package authors to either remove "Description" so that the README will show up? Or suggest to write a better "Description"? Or make use of both "Description" and "README"? Or change the layout to not reserve so much space here?).

**Comment by kiranandcode** [comment]
Maybe a hint in opam lint when a project has a description section and a readme could be helpful? 

I assumed both the synopsis and description were necessary fields for an opam file, I had no idea that it wasn't and in fact, could be reducing the quality of my package descriptions.

I've been adding descriptions to all my projects for a while now, I can't remember the exact reason I started - either at some point a tool (dune or opam lint) was complaining if I didn't have it, or because most opam files in projects I'd look at for reference would have description fields.

If opam lint would warn about that, I guess that would be a good way of letting users know about this organically.

**Comment by sabine** [comment]
@Gopiandcode I Indeed, adding an opam description should **not** reduce the quality of your package overview page on ocaml.org.

This is, as I understand it, either
(1) a layout issue with ocaml.org (reserving so much space that it will look empty, considering the average package description), or
(2) lack of specification and unclear communication of what kind of descriptions (length, content) the OCaml community expects package authors to provide.

All I can see is that something is going very wrong for some packages and that I as a user of ocaml.org would have gotten more use out of the readme in this case. 

Either way, it's nothing to be blamed on package authors at all. Just a thing that we need to sort out as a community, improve ocaml.org, and improve the package publishing experience and documentation.

I like your idea of using `opam lint` to give hints on what is expected!
