### ISSUE TITLE
Package documentation only contains one library for Frama-C

### ISSUE THREAD

**Issue by tmattio** [ocaml/ocaml.org#962]
The documentation for [Frama-C](https://ocaml.org/p/frama-c/latest/doc/index.html) only contains one of the libraries of the package: qed. The package contains much more libraries than this, so this seems to be an issue with how we generate the doc in for this particular package. 

Dev repository for Frama-C: https://git.frama-c.com/pub/frama-c

cc @AllanBlanchard

**Comment by cuihtlauac** [comment]
The page https://ocaml.org/p/frama-c/latest/doc/index.html only list the `qed` library.

This is consistent with https://docs-data.ocaml.org/current/p/frama-c/26.1/package.json which also only lists `qed`

```
curl -s https://docs-data.ocaml.org/current/p/frama-c/26.1/package.json | jq ".libraries[].name"
```

In order to generate frama-c documentation with voodoo, here is what I did:

1. Clone voodoo
2. `opam switch create . 4.14.1 --no-install` (don't do `make switch`)
3. `make deps`
4. `make build`
5. downgrade ocplib-simplex to 0.4 (`opam install ocplib-simplex.0.4`, last version is 0.5 and seems to be incompatible with alt-ergo, required by frama-c)
6. install frama-c (`opam install frama-c`)
7. `make example`
8. `make frama-c`
9. `(cd _generated ; opam exec -- dune exec -- voodoo-gen -o output)`


Using this context, the following command:
```
cat ./_generated/linked/p/frama-c/26.1/package.json | jq ".libraries[].name"
```

Claims there are 51 libraries in frama-c

**Comment by cuihtlauac** [comment]
![Screenshot_2023-03-04_07-20-29](https://user-images.githubusercontent.com/1917592/222879641-3c640556-92da-4943-bf59-cde8639f1cdb.png)

To get there:

1. Recompiled voodoo like described before.
2. Installed frama-c and have voodoo generate its doc
3. Served it locally `webfsd -F -p 8040 -r _generated/output` (couldn't install dream-serve)
4. Patched, compiled and launched ocaml.org (not setting OCAMLORG_DOC_URL):
```
diff --git a/src/ocamlorg_package/lib/ocamlorg_package.ml b/src/ocamlorg_package/lib/ocamlorg_package.ml
index a2430816..cbb91fca 100644
--- a/src/ocamlorg_package/lib/ocamlorg_package.ml
+++ b/src/ocamlorg_package/lib/ocamlorg_package.ml
@@ -341,12 +341,12 @@ module Module_map = Module_map
 let package_url ~kind name version =
   match kind with
   | `Package ->
-      "https://docs-data.ocaml.org/current/" ^ "p/" ^ name ^ "/" ^ version ^ "/"
-      (* "http://127.0.0.1:8000/" ^ "p/" ^ name ^ "/" ^ version ^ "/" *)
+      (* "https://docs-data.ocaml.org/current/" ^ "p/" ^ name ^ "/" ^ version ^ "/" *)
+      "http://localhost:8040/" ^ "p/" ^ name ^ "/" ^ version ^ "/"
   | `Universe s ->
-      "https://docs-data.ocaml.org/current/" ^ "u/" ^ s ^ "/" ^ name ^ "/"
-      ^ version ^ "/"
-(* "http://127.0.0.1:8000/" ^ "u/" ^ s ^ "/" ^ name ^ "/" ^ version ^ "/" *)
+      (* "https://docs-data.ocaml.org/current/" ^ "u/" ^ s ^ "/" ^ name ^ "/"
+      ^ version ^ "/" *)
+ "http://127.0.0.1:8040/" ^ "u/" ^ s ^ "/" ^ name ^ "/" ^ version ^ "/"
 
 (* FIXME: rename to package_path when fallback is no longer necessary *)
 let old_package_url ~kind name version =
```

**Comment by sabine** [comment]
That looks excellent!

Now the interesting questions are:
1. with ocplib-simplex 0.4 being possibly incompatible with alt-ergo, why did the documentation build at all? I see errors on many of the other frama-c versions.
2. does explicitly setting the ocplib-simplex version make the documentation build successfully in the pipeline? :thinking:

**Comment by AllanBlanchard** [comment]
On the other Frama-C versions, I believe that the reason is related to the fact that when both GTK2 and GTK3 dependencies are proposed in the opam file, the solver choose GTK2 which is not compatible anymore with most systems.

**Comment by AllanBlanchard** [comment]
For the current version, I assume that because Frama-C is made of several (optional) `dune-project`s, it builds what it can.

**Comment by cuihtlauac** [comment]
Thanks, @AllanBlanchard. Do you mean I should see even more libraries than the set of 51 collected in the built I did?

**Comment by AllanBlanchard** [comment]
No, it was not clear, my answer was about the question "why did the documentation build at all?".

What we generate via Dune is available here: https://www.frama-c.com/download/frama-c-26.1-Iron-api.tar.gz

It seems that the comparison is not easy because Ocaml.org does not organizes the modules like Dune does.

**Comment by sabine** [comment]
It looks like that was a transient problem (possibly with the solver? :thinking:) which is resolved for now. Nothing is wrong with `frama-c` and the docs at https://ocaml.org/p/frama-c/latest/doc/index.html as of now show all 51 libraries.
